version: 2.1
jobs:
  one:
    docker:
      - image: cimg/ruby:2.6.8
      auth:
        username: addyboy07
        password: Adam@1234
    steps:
      - checkout
      - run: echo "A first Hello"
      - run: sleep 25
  two: 
    docker:
      - image: cimg/ruby:3.0.2
      auth:
        username: addyboy07
        password: Adam@1234
    steps:
      - checkout
      - run: echo "A more familiar Hi"
      - run: sleep 15
  workflows:
    version: 2
    one_and_two:
      jobs:
         - one
         - two
